# 1) Load class from module...
from PoseModule import Pose_3D

# 2) Create pose object from class...
pose = Pose_3D()

# 3) Create skeletons as class method...
pose.create_skeleton()

# 4) Create video file as class method...
pose.create_video_from_skeleton()