all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
- - 14
- - 15
- - 16
- - 17
- - 18
- - 19
- - 20
- - 21
- - 22
- - 23
- - 24
all_joints_names:
- chin
- leftear
- rightear
- lefteye1
- lefteye2
- lefteye3
- lefteye4
- righteye1
- righteye2
- righteye3
- righteye4
- nose1
- nose2
- nose3
- nose4
- lefteyebrow1
- lefteyebrow2
- lefteyebrow3
- righteyebrow1
- righteyebrow2
- righteyebrow3
- mouth1
- mouth2
- mouth3
- mouth4
alpha_r: 0.02
batch_size: 1
clahe: true
claheratio: 0.1
cropratio: 0.4
dataset: training-datasets\iteration-1\UnaugmentedDataSet_DLCApr14\DLC_Guillermo95shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: 'D:\3DBHVR\FacialExpression_20210414\DLC-Guillermo-2021-04-14\dlc-models\iteration-0\DLCApr14-trainset95shuffle1\train\snapshot-1030000'
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets\iteration-1\UnaugmentedDataSet_DLCApr14\Documentation_data-DLC_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 25
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: D:/3DBHVR/FacialExpression_20210414/DLC-Guillermo-2021-04-14
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
